export const LOAD_FEATURES_SUCCESS = "LOAD_FEATURES_SUCCESS";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_FEATURES_START = "API_CALL_FEATURES_START";
export const GET_CURRENT_POSITION_REQUEST = "GET_CURRENT_POSITION_REQUEST";
export const GET_CURRENT_POSITION_SUCCESS = "GET_CURRENT_POSITION_SUCCESS";
export const GET_CURRENT_POSITION_ERROR = "GET_CURRENT_POSITION_ERROR";
export const GET_CURRENT_LOCATION_NAME_SUCCESS = "GET_CURRENT_LOCATION_NAME_SUCCESS";
export const UPDATE_COORDINATES = "UPDATE_COORDINATES";